import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { analyzeProject } from "../dist/analyzer.js";
import { generateReadme } from "../dist/generator.js";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const checkOnly = process.argv.includes("--check");

const examples = [
  {
    slug: "typescript-cli",
    title: "TypeScript CLI",
    fixture: "test/fixtures/typescript-cli",
    template: "cli",
    value: "CLI scripts, TypeScript metadata, and maintainer-friendly run/test sections."
  },
  {
    slug: "vite-web",
    title: "Vite Web App",
    fixture: "test/fixtures/vite-web",
    template: "web",
    value: "Web-app scripts and framework detection for local development docs."
  },
  {
    slug: "npm-workspace",
    title: "npm Workspace",
    fixture: "test/fixtures/npm-workspace",
    template: "auto",
    value: "Workspace patterns and package summaries for monorepo onboarding."
  },
  {
    slug: "python-package",
    title: "Python Package",
    fixture: "test/fixtures/python-package",
    template: "library",
    value: "Non-Node metadata from pyproject.toml with library-style output."
  },
  {
    slug: "rust-crate",
    title: "Rust Crate",
    fixture: "test/fixtures/rust-crate",
    template: "library",
    value: "Cargo metadata, language detection, and library documentation defaults."
  },
  {
    slug: "go-module",
    title: "Go Module",
    fixture: "test/fixtures/go-module",
    template: "library",
    value: "Go module names and lightweight repository structure detection."
  }
];

function slash(filePath) {
  return filePath.replaceAll("\\", "/");
}

function commandFor(example) {
  return `npm run dev -- ${example.fixture} --dry-run --template ${example.template} --no-badges`;
}

function renderExampleReadme(example, readme) {
  return `<!-- Generated by npm run examples:generate from ${example.fixture}. Do not edit by hand. -->

${readme.trim()}

---

Regenerate this example:

\`\`\`bash
npm run examples:generate
\`\`\`
`;
}

function renderFacts(facts) {
  const parts = [
    facts.languages.length ? facts.languages.join(", ") : "lightweight project",
    facts.frameworks.length ? facts.frameworks.join(", ") : undefined,
    facts.workspaces ? `${facts.workspaces.packages.length} workspace packages` : undefined
  ].filter(Boolean);

  return parts.join("; ");
}

function renderGallery(rows) {
  const tableRows = rows
    .map((row) => `| [${row.title}](../examples/gallery/${row.slug}/README.generated.md) | \`${row.template}\` | ${row.factsSummary} | \`${commandFor(row)}\` |`)
    .join("\n");

  return `# Generated README Gallery

This gallery shows deterministic README output generated from real fixture-style project shapes.

Each example is regenerated from local metadata with \`npm run examples:generate\`, so visitors can inspect the output before trying the CLI on their own repositories.

| Example | Template | Detected Shape | Preview Command |
| --- | --- | --- | --- |
${tableRows}

## Regenerate

\`\`\`bash
npm run build
npm run examples:generate
npm run examples:check
\`\`\`

## Why This Matters

The examples make \`readme-forge\` easier to evaluate from the repository page:

- maintainers can compare output across CLI, web, workspace, Python, Rust, and Go projects
- contributors get concrete fixtures for template and detector improvements
- reviewers can verify that generated docs are grounded in detected project metadata
`;
}

async function collectOutputs() {
  const outputs = [];
  const galleryRows = [];

  for (const example of examples) {
    const fixtureRoot = path.join(repoRoot, example.fixture);
    const facts = await analyzeProject(fixtureRoot);
    const readme = generateReadme(facts, example.template, { badges: false });
    const outputPath = path.join(repoRoot, "examples", "gallery", example.slug, "README.generated.md");
    const factsSummary = renderFacts(facts);

    outputs.push({
      path: outputPath,
      content: renderExampleReadme(example, readme)
    });
    galleryRows.push({
      ...example,
      factsSummary
    });
  }

  outputs.push({
    path: path.join(repoRoot, "docs", "GALLERY.md"),
    content: renderGallery(galleryRows)
  });

  return outputs;
}

async function main() {
  const outputs = await collectOutputs();
  const outOfSync = [];

  for (const output of outputs) {
    if (checkOnly) {
      const existing = await readFile(output.path, "utf8").catch(() => "");
      if (existing !== output.content) outOfSync.push(slash(path.relative(repoRoot, output.path)));
      continue;
    }

    await mkdir(path.dirname(output.path), { recursive: true });
    await writeFile(output.path, output.content, "utf8");
    console.log(`Wrote ${slash(path.relative(repoRoot, output.path))}`);
  }

  if (checkOnly && outOfSync.length) {
    console.error(`Generated gallery is out of sync:\n${outOfSync.map((filePath) => `- ${filePath}`).join("\n")}`);
    process.exitCode = 1;
    return;
  }

  if (checkOnly) {
    console.log("Generated gallery is in sync.");
  }
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
